

-- drop fulltext on ATTRIBUTE, because InnoDB does not support full text indexes
lock tables ATTRIBUTE write; write;
alter table ATTRIBUTE drop key VALUE;
unlock tables;

-- change all tables to InnoDB
lock tables ATTRIBUTE write; write;
alter table ACL_ROWS engine=InnoDB;
unlock tables;
lock tables ACLS write; write;
alter table ACLS engine=InnoDB;
unlock tables;
lock tables ATTRIBUTE write; write;
alter table ATTRIBUTE engine=InnoDB;
unlock tables;
lock tables CACHE write;
alter table CACHE engine=InnoDB;
unlock tables;
lock tables COMPLEX_ATTR_FIELD write;
alter table COMPLEX_ATTR_FIELD engine=InnoDB;
unlock tables;
lock tables COMPLEX_ATTR_ROW write;
alter table COMPLEX_ATTR_ROW engine=InnoDB;
unlock tables;
lock tables DATAELEM write;
alter table DATAELEM engine=InnoDB;
unlock tables;
lock tables DATASET write;
alter table DATASET engine=InnoDB;
unlock tables;
lock tables DOC write;
alter table DOC engine=InnoDB;
unlock tables;
lock tables DS_TABLE write;
alter table DS_TABLE engine=InnoDB;
unlock tables;
lock tables DST2ROD write;
alter table DST2ROD engine=InnoDB;
unlock tables;
lock tables DST2TBL write;
alter table DST2TBL engine=InnoDB;
unlock tables;
lock tables FK_RELATION write;
alter table FK_RELATION engine=InnoDB;
unlock tables;
lock tables FXV write;
alter table FXV engine=InnoDB;
unlock tables;
lock tables HARV_ATTR write;
alter table HARV_ATTR engine=InnoDB;
unlock tables;
lock tables HARV_ATTR_FIELD write;
alter table HARV_ATTR_FIELD engine=InnoDB;
unlock tables;
lock tables HLP_AREA write;
alter table HLP_AREA engine=InnoDB;
unlock tables;
lock tables HLP_SCREEN write;
alter table HLP_SCREEN engine=InnoDB;
unlock tables;
lock tables M_ATTRIBUTE write;
alter table M_ATTRIBUTE engine=InnoDB;
unlock tables;
lock tables M_COMPLEX_ATTR write;
alter table M_COMPLEX_ATTR engine=InnoDB;
unlock tables;
lock tables M_COMPLEX_ATTR_FIELD write;
alter table M_COMPLEX_ATTR_FIELD engine=InnoDB;
unlock tables;
lock tables NAMESPACE write;
alter table NAMESPACE engine=InnoDB;
unlock tables;
lock tables ROD_ACTIVITIES write;
alter table ROD_ACTIVITIES engine=InnoDB;
unlock tables;
lock tables TBL2ELEM write;
alter table TBL2ELEM engine=InnoDB;
unlock tables;