ALTER TABLE T_VOCABULARY_FOLDER ADD COLUMN FOLDER_NAME varchar(100) not null DEFAULT 'common';

alter table T_VOCABULARY_FOLDER add index (FOLDER_NAME);
ALTER TABLE T_VOCABULARY_FOLDER DROP INDEX UNIQUE_VOCABULARY;
ALTER TABLE T_VOCABULARY_FOLDER ADD CONSTRAINT UNIQUE_VOCABULARY UNIQUE (FOLDER_NAME, IDENTIFIER, WORKING_COPY);