ALTER TABLE T_VOCABULARY_CONCEPT ADD COLUMN OBSOLETE_DATE timestamp NULL default NULL;
ALTER TABLE T_VOCABULARY_CONCEPT ADD COLUMN CREATION_DATE timestamp NOT NULL default now();
UPDATE T_VOCABULARY_CONCEPT SET CREATION_DATE = now();
