-- New T_VOCABULARY_CONCEPT_ATTRIBUTE table
create table T_VOCABULARY_CONCEPT_ATTRIBUTE (
    ID int(10) unsigned not null auto_increment,
    M_ATTRIBUTE_ID int(10) unsigned not null,
    VOCABULARY_CONCEPT_ID int(10) unsigned not null,
    ATTR_VALUE text not null,
    LANGUAGE varchar(10),
    primary key (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE T_VOCABULARY_CONCEPT_ATTRIBUTE ADD CONSTRAINT FK_CONCEPT_ATTRIBUTE_ID FOREIGN KEY (VOCABULARY_CONCEPT_ID) REFERENCES T_VOCABULARY_CONCEPT(VOCABULARY_CONCEPT_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE T_VOCABULARY_CONCEPT_ATTRIBUTE ADD CONSTRAINT FK_M_ATTRIBUTE_ATTRIBUTE_ID FOREIGN KEY (M_ATTRIBUTE_ID) REFERENCES M_ATTRIBUTE(M_ATTRIBUTE_ID) ON DELETE CASCADE ON UPDATE CASCADE;

-- M_ATTRIBUTE table modification
ALTER TABLE M_ATTRIBUTE ADD COLUMN LANGUAGE_USED BOOLEAN default 0;
ALTER TABLE M_ATTRIBUTE ADD COLUMN DATA_TYPE enum('reference','','string','integer','decimal','boolean','dateTime','date') DEFAULT NULL;

-- T_VOCABULARY_CONCEPT modification
ALTER TABLE T_VOCABULARY_CONCEPT ADD COLUMN ORIGINAL_CONCEPT_ID int(10) unsigned;

-- Insert new attributes
INSERT INTO M_ATTRIBUTE (NAME, SHORT_NAME, DEFINITION, DISP_TYPE, DISP_ORDER, DISP_WHEN, DISP_MULTIPLE, LANGUAGE_USED, DATA_TYPE, OBLIGATION, DISP_WIDTH)
VALUES ('Alternative label', 'altLabel', '', 'text', 41, 512, '1', 1, 'string', 'O', 60);
INSERT INTO M_ATTRIBUTE (NAME, SHORT_NAME, DEFINITION, DISP_TYPE, DISP_ORDER, DISP_WHEN, DISP_MULTIPLE, LANGUAGE_USED, DATA_TYPE, OBLIGATION, DISP_WIDTH)
VALUES ('Hidden label', 'hiddenLabel', '', 'text', 42, 512, '1', 1, 'string', 'O', 60);
INSERT INTO M_ATTRIBUTE (NAME, SHORT_NAME, DEFINITION, DISP_TYPE, DISP_ORDER, DISP_WHEN, DISP_MULTIPLE, LANGUAGE_USED, DATA_TYPE, OBLIGATION, DISP_WIDTH)
VALUES ('Scope note', 'scopeNote', '', 'text', 43, 512, '1', 0, 'string', 'O', 60);
INSERT INTO M_ATTRIBUTE (NAME, SHORT_NAME, DEFINITION, DISP_TYPE, DISP_ORDER, DISP_WHEN, DISP_MULTIPLE, LANGUAGE_USED, DATA_TYPE, OBLIGATION, DISP_WIDTH)
VALUES ('Change note', 'changeNote', '', 'text', 44, 512, '1', 0, 'string', 'O', 60);
INSERT INTO M_ATTRIBUTE (NAME, SHORT_NAME, DEFINITION, DISP_TYPE, DISP_ORDER, DISP_WHEN, DISP_MULTIPLE, LANGUAGE_USED, DATA_TYPE, OBLIGATION, DISP_WIDTH)
VALUES ('Editorial note', 'editorialNote', '', 'text', 45, 512, '1', 0, 'string', 'O', 60);
INSERT INTO M_ATTRIBUTE (NAME, SHORT_NAME, DEFINITION, DISP_TYPE, DISP_ORDER, DISP_WHEN, DISP_MULTIPLE, LANGUAGE_USED, DATA_TYPE, OBLIGATION, DISP_WIDTH)
VALUES ('History note', 'historyNote', '', 'text', 46, 512, '1', 0, 'string', 'O', 60);
INSERT INTO M_ATTRIBUTE (NAME, SHORT_NAME, DEFINITION, DISP_TYPE, DISP_ORDER, DISP_WHEN, DISP_MULTIPLE, LANGUAGE_USED, DATA_TYPE, OBLIGATION, DISP_WIDTH)
VALUES ('Example', 'example', '', 'text', 47, 512, '1', 0, 'string', 'O', 60);
INSERT INTO M_ATTRIBUTE (NAME, SHORT_NAME, DEFINITION, DISP_TYPE, DISP_ORDER, DISP_WHEN, DISP_MULTIPLE, LANGUAGE_USED, DATA_TYPE, OBLIGATION, DISP_WIDTH)
VALUES ('Label', 'label', '', 'text', 11, 512, '1', 1, 'string', 'O', 60);
INSERT INTO M_ATTRIBUTE (NAME, SHORT_NAME, DEFINITION, DISP_TYPE, DISP_ORDER, DISP_WHEN, DISP_MULTIPLE, LANGUAGE_USED, DATA_TYPE, OBLIGATION, DISP_WIDTH, DISP_HEIGHT)
VALUES ('Definition', 'multiLangDefinition', '', 'textarea', 12, 512, '1', 1, 'string', 'O', 50, 3);
INSERT INTO M_ATTRIBUTE (NAME, SHORT_NAME, DEFINITION, DISP_TYPE, DISP_ORDER, DISP_WHEN, DISP_MULTIPLE, LANGUAGE_USED, DATA_TYPE, OBLIGATION, DISP_WIDTH)
VALUES ('Notation', 'notation', '', 'text', 13, 512, '1', 1, 'string', 'O', 60);
