ALTER TABLE T_VOCABULARY_CONCEPT_ATTRIBUTE CHANGE COLUMN ATTR_VALUE ATTR_VALUE TEXT NULL AFTER VOCABULARY_CONCEPT_ID;
ALTER TABLE T_VOCABULARY_CONCEPT_ATTRIBUTE ADD COLUMN LINK_TEXT varchar(255);
ALTER TABLE T_VOCABULARY_CONCEPT_ATTRIBUTE ADD COLUMN RELATED_CONCEPT_ID int(10) unsigned;
ALTER TABLE T_VOCABULARY_CONCEPT_ATTRIBUTE ADD CONSTRAINT FK_RELATED_CONCEPT_ID FOREIGN KEY (RELATED_CONCEPT_ID) REFERENCES T_VOCABULARY_CONCEPT(VOCABULARY_CONCEPT_ID) ON DELETE CASCADE ON UPDATE CASCADE;

-- Insert new attributes
INSERT INTO M_ATTRIBUTE (NAME, SHORT_NAME, DEFINITION, DISP_TYPE, DISP_ORDER, DISP_WHEN, DISP_MULTIPLE, LANGUAGE_USED, DATA_TYPE, OBLIGATION, DISP_WIDTH, RDF_PROPERTY)
VALUES ('Broader concepts', 'broaderLocalConcept', '', 'select', 51, 512, '1', 0, 'reference', 'O', 60, 'skos:broader');

INSERT INTO M_ATTRIBUTE (NAME, SHORT_NAME, DEFINITION, DISP_TYPE, DISP_ORDER, DISP_WHEN, DISP_MULTIPLE, LANGUAGE_USED, DATA_TYPE, OBLIGATION, DISP_WIDTH, RDF_PROPERTY)
VALUES ('Narrower concepts', 'narrowerLocalConcept', '', 'select', 52, 512, '1', 0, 'reference', 'O', 60, 'skos:narrower');

INSERT INTO M_ATTRIBUTE (NAME, SHORT_NAME, DEFINITION, DISP_TYPE, DISP_ORDER, DISP_WHEN, DISP_MULTIPLE, LANGUAGE_USED, DATA_TYPE, OBLIGATION, DISP_WIDTH, RDF_PROPERTY)
VALUES ('Related concepts', 'relatedLocalConcept', '', 'select', 53, 512, '1', 0, 'reference', 'O', 60, 'skos:related');